version: "2.7"
http:
  middleware: [ "http_metrics", "static", "gzip", "headers", "proxy_ip_parser" ]
  address: "0.0.0.0:8080"
  trusted_subnets: [ "0.0.0.0/0" ]
  headers:
    cors:
      allowed_headers: "*"
  max_request_size: 20
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  pool:
    allocate_timeout: 10s
    destroy_timeout: 10s
    supervisor:
      exec_ttl: 60s
server:
  command: "php ./vendor/bin/roadrunner-worker"
rpc:
  listen: tcp://127.0.0.1:6001
metrics:
  # Prometheus client address (path /metrics added automatically).
  address: 0.0.0.0:8081
status:
  # Host and port to listen on (eg.: `127.0.0.1:2114`). Use the following URL: http://127.0.0.1:2114/health?plugin=http
  # Multiple plugins must be separated using "&" - http://127.0.0.1:2114/health?plugin=http&plugin=rpc where "http" and
  # "rpc" are active (connected) plugins.
  address: 0.0.0.0:8082
logs:
  mode: development
  level: debug
  encoding: json
